#!/bin/bash

exec 2>&1

############# PROJECT SETUP #############################
echo "Copying source files"
cp -r {{pkg.path}}/public_html/* {{pkg.svc_data_path}}/.

chmod +x {{pkg.svc_data_path}}
chown -RL hab:hab {{pkg.svc_data_path}}

cp {{pkg.svc_config_path}}/config.inc.php {{pkg.svc_data_path}}/config.inc.php

chown hab:hab {{pkg.svc_data_path}}/config.inc.php

############# NGINX SETUP #############################
mkdir -p {{pkg.svc_var_path}}/nginx
chown hab:hab {{pkg.svc_var_path}}
